### ISSUE TITLE
Softdevice flashing

### ISSUE THREAD

**Issue by jeremypoulter** [platformio/platform-nordicnrf52#10]
I am probably missing something really obvious, but how do you flash a softdevice under Platform IO?

**Comment by valeros** [comment]
Hi @jeremypoulter ! The resulting binary is merged from the user application and selected softdevice.
https://github.com/platformio/platform-nordicnrf52/blob/develop/builder/main.py#L130

**Comment by jeremypoulter** [comment]
I am not so sure that is what this line is doing. Certainly the end result does not work until I use Arduino IDE to flash the Soft Device. Then everything is ok.

**Comment by valeros** [comment]
We use a special tool called `SRecord` to combine main application and the softdevice binary.
Could you please describe in greater detail what exactly doesn't work? A simple blink, BLE functionality? What is your board? Did you use `build_flags` to specify the softdevice version?
Thanks!

**Comment by jeremypoulter** [comment]
It is our own custom board with a [Liard BL652 module](https://www.lairdtech.com/products/bl652-ble-module). I can see the soft device being merged into the firmware and the result being flashed:

```
C:\Users\jeremy\.platformio\packages\tool-sreccat\srec_cat C:\Users\jeremy\.platformio\packages\framework-arduinonordicnrf5@src-d2a7ef78dfbec2ba5b0b645c94ed87d3\cores\nRF5\SDK\components\softdevice\s132\hex\s132_
nrf52_2.0.1_softdevice.hex -intel .pioenvs\nudge_laser\userfirmware.hex -intel -o .pioenvs\nudge_laser\firmware.hex -intel --line-length=44
"openocd" -s C:\Users\jeremy\.platformio\packages\tool-openocd -f scripts/interface/jlink.cfg -c "transport select swd" -f scripts/target/nrf52_arduino.cfg -c "program {{.pioenvs\nudge_laser\firmware.hex}} verify
 reset; shutdown;"
```

but the  code fails to execute until the device is flashed with the softdevice using Arduino IDE and the nRF5FlashSoftDevice.jar tool. These modules do come pre-flashed with 'smartBASIC' so maybe there is some state that is erased by nRF5FlashSoftDevice.jar?

**Comment by valeros** [comment]
I haven't dealt with BL652, but probably you are right and `nRF5FlashSoftDevice.jar` erases the entire MCU flash memory before flashing the softdevice.

**Comment by jzumaeta** [comment]
Hi, I have the same problem with nRF51-DK board. Anyone knows how to solve this issue?

**Comment by ArtemPisarenko** [comment]
Same problem. It's absolutely unclear how to develop BLE functionality using PlatformIO IDE for VSCode. I just follow latest [official tutorial](https://docs.platformio.org/en/stable/tutorials/nordicnrf52/arduino_debugging_unit_testing.html) and can't get working example from it. It succeeds with build, upload(seems to succeed) and debug, but actual flashed firmware either doesn't run at all (instead last flashed non-BLE application gets running when board powered on), or hangs on entering softdevice (when run debug session). The reason is that upload stage **silently** fails to flash softdevice saying `"Warning! Cannot find an appropriate softdevice binary!"`. I discovered that `~/.platformio/packages/framework-arduinonordicnrf5/cores/nRF5/SDK/components/softdevice/*/hex` folders are empty. Maybe it's normal, that package doesn't ship with these proprietary firmwares, but documentation doesn't say absolutely nothing about what additional steps required in order to get installation complete specifically for VSCode. I found these steps for Arduino IDE but they seems to be incompatible with VSCode.
