### ISSUE TITLE
Add support for E73-TBB and nRF52840-Kit boards

### ISSUE THREAD

**Issue by zayats1** [platformio/platform-nordicnrf52#75]
In aliexpress i saw these boards: 
1) https://aliexpress.com/item/32968664414.html
2) https://aliexpress.com/item/33019705710.html

I didn't find it in PIO boards.
I think  nrf52 boards  programs with mbed os or arduino  framework.

sory for my English

**Comment by adamhun94** [comment]
+1 for the **E73** board. Though I have a E73-2G4M04S1B variant, I think it would work as well (I really hope so). Previously I was able to compile my code with [sandeepmistry/arduino-nRF5 ](https://github.com/sandeepmistry/arduino-nRF5) core in the Arduino ide as a "Generic NRF52 board" with SoftDevice132 and using openOCD on my Raspberry Pi to flash it. Although I always get "_target halted due to debug-request, current mode: Thread_" when flashing, the code works.

My ultimate plan is to build my fw with platformio (on my RPi), and flash my chip with it with a debugging possibility. Do you think it would be possible? I'm kinda new to these things, mostly programmed Arduinos only before.

Thanks for your hard work!
